version: '3'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    restart: on-failure:1
    ports:
      - "1884:1883"
      - "8161:8161"
    container_name: activemq
  nifi:
    image: apache/nifi:1.18.0
    restart: on-failure:1
    volumes:
      - ./flow:/opt/nifi/nifi-current/flow
      - ./logs:/opt/nifi/nifi-current/logs
    ports:
      - "8181:8181"
    environment:
      NIFI_WEB_HTTP_PORT: 8181
      NIFI_SENSITIVE_PROPS_KEY: OyXbbjYjE0iXsJzSGuIn
    entrypoint: > 
      bash -c "echo Overwriting entrypoint && echo Replace path for flow.xml.gz && sed -i 's#=./conf/flow.xml.gz#=./flow/flow.xml.gz#g' /opt/nifi/nifi-current/conf/nifi.properties && /opt/nifi/scripts/start.sh"
